# Generated by Django 5.0.7 on 2024-08-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porject',
            new_name='Project',
        ),
    ]
